#!/usr/bin/env node
// Generates src/version.js with the current git short-hash.
// Runs as preinstall and prestart so the deployed container always
// reports its real commit hash (instead of whatever was checked in).
//
// Strategy:
//   1. Try GIT_COMMIT_HASH env var (set by some CI systems)
//   2. Try COOLIFY_COMMIT_SHA env var (set by Coolify 4.x — actually NOT injected by default,
//      but we read it for future-proofing; if not set, we fall back to local git)
//   3. Try `git rev-parse --short HEAD` (works in local dev/CI with full clone)
//   4. Fall back to "unknown"
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';

let hash = process.env.GIT_COMMIT_HASH || process.env.COOLIFY_COMMIT_SHA;

if (!hash) {
  try {
    hash = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
  } catch (e) {
    hash = 'unknown';
  }
}

// Strip any whitespace/newlines
hash = String(hash).trim().split(/\s+/)[0] || 'unknown';

const out = `// AUTO-GENERATED by scripts/generate-version.js — do not edit manually
export const VERSION = '${hash}';
`;

mkdirSync('src', { recursive: true });
writeFileSync('src/version.js', out);
process.stdout.write(`[version] ${hash}\n`);