#!/usr/bin/env node
// Generates src/version.js with the current git short-hash.
// Runs as preinstall and prestart so the deployed container always
// reports its real commit hash (instead of whatever was checked in).
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

let hash = 'unknown';
try {
  hash = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
} catch (e) {
  // CI or no-git fallback — leave as-is
}

const out = `// AUTO-GENERATED by scripts/generate-version.js — do not edit manually
export const VERSION = '${hash}';
`;

mkdirSync('src', { recursive: true });
writeFileSync('src/version.js', out);
process.stdout.write(`[version] ${hash}\n`);